BestRestaurant/Models/BestRestaurantContext.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Models
{
  public class BestRestaurantContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public virtual DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<Rating> Ratings { get; set; }
    public BestRestaurantContext(DbContextOptions options) : base(options) {}
  }
}

BestRestaurant/Models/Cuisine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BestRestaurant.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
    public int CuisineId { get; set; }
    public string Name { get; set; }
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public string Region { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurant/Models/Rating.cs
namespace BestRestaurant.Models
{
  public class Rating
  {
    public int RatingId { get; set; }
    public int RestaurantId { get; set; }
    public decimal Score { get; set; }
    public string Review { get; set; }
    public virtual Restaurant Restaurant { get; set; }
  }
}

BestRestaurant/Models/Restaurant.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Restaurant
  {
    public Restaurant()
    {
      this.Ratings = new HashSet<Rating>();
    }
    public int RestaurantId { get; set; }
    public int CuisineId { get; set; }
    public string Name { get; set; }
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]  //allows in workbench to set a default value. rather than null. 
    public string Location { get; set; }
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public string PhoneNumber { get; set; }
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Rating { get; set; }
    public virtual Cuisine Cuisine { get; set; }
    public virtual ICollection<Rating> Ratings { get; set; }
  }
}

BestRestaurant/Controllers/CuisineController.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class CuisineController : Controller
  {
    private readonly BestRestaurantContext _db;

    public CuisineController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model); 
    }

    public ActionResult Show(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.Include(cuisines => cuisines.Restaurants).FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }
  }
}

BestRestaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurant.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

BestRestaurant/Controllers/RatingController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class RatingController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RatingController(BestRestaurantContext db)
    {
      _db = db;
    }
    public ActionResult Create(int id)
    {
      ViewBag.RestaurantId = id;
      return View();
    }

    [HttpPost]
    public ActionResult Create(Rating rating)
    {
      _db.Ratings.Add(rating);
      _db.SaveChanges();
      return RedirectToAction("Show", "Restaurant", new {id = rating.RestaurantId});
    }

    public ActionResult Edit(int id)
    {
      Rating thisRating = _db.Ratings.FirstOrDefault(ratings => ratings.RatingId == id);
      return View(thisRating);
    }

    [HttpPost]
    public ActionResult Edit(Rating rating)
    {
      _db.Entry(rating).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Show", "Restaurant", new {id = rating.RestaurantId});
    }

    public ActionResult Delete(int id)
    {
      Rating thisRating = _db.Ratings.FirstOrDefault(ratings => ratings.RatingId == id);
      return View(thisRating);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Rating thisRating = _db.Ratings.FirstOrDefault(ratings => ratings.RatingId == id);
      _db.Ratings.Remove(thisRating);
      _db.SaveChanges();
      return RedirectToAction("Show", "Restaurant", new {id = thisRating.RestaurantId});
    }
  }
}

BestRestaurant/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Linq;
using System;

namespace BestRestaurant.Controllers
{
  public class RestaurantController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RestaurantController(BestRestaurantContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Show(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.Include(restaurants => restaurants.Cuisine).Include(restaurants => restaurants.Ratings).FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      
      var AverageScore = 
        from r in _db.Ratings
        group r by r.RestaurantId into res
        where res.Key == thisRestaurant.RestaurantId
        select res.Average(ratings => ratings.Score);


      ViewBag.avgScore =  Math.Round(AverageScore.FirstOrDefault(), 1); 
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Views/Cuisine/Details.cshtml
@{
  Layout = "_Layout";
}

BestRestaurant/Views/Cuisine/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model List<BestRestaurant.Models.Cuisine>;

<h1>Cuisine</h1>

<ul>
  @foreach(Cuisine cuisine in Model)
  {
    <li>@Html.ActionLink($"{cuisine.Name}", "Show", new { id = cuisine.CuisineId })</li>
  }
</ul>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Cuisine/Show.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model BestRestaurant.Models.Cuisine;

<h1>Cuisine Details:</h1>
<hr />
<h2>@Html.DisplayFor(model => model.Name)</h2>
<h3>Region: @Html.DisplayFor(model => model.Region)</h3>

<h4>Restaurants:</h4>
<ul>
@if(Model.Restaurants.Count == 0)
{
<p>No Restaurants Found</p>
}

@foreach (Restaurant restaurant in @Model.Restaurants)
{
<li>@Html.ActionLink($"{restaurant.Name}", "Show", "Restaurant", new { id = restaurant.RestaurantId })</li>
}
</ul>

<p>@Html.ActionLink("Back to Cuisines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Lonny's Restaurants!</h1>

<div class="splash"><p>@Html.ActionLink("See all Restaurants", "Index", "Restaurant")     ||       @Html.ActionLink("See all Cuisines", "Index", "Cuisine")</p>
</div>

BestRestaurant/Views/Rating/Create.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurant.Models
@model BestRestaurant.Models.Rating;

<h1>Add new Rating</h1>
<br>
@using (Html.BeginForm())
{
  <div class ="form-group">
    <input type="hidden" name="RestaurantId" id="RestaurantId" value="@ViewBag.RestaurantId" />
    <h4>@Html.LabelFor(model => model.Score)</h4>
    @Html.TextBoxFor(model => model.Score, new{ @class = "form-control"})
  
    <h4>@Html.LabelFor(model => model.Review)</h4>
    @Html.TextBoxFor(model => model.Review, new{ @class = "form-control"})
  </div>
  <input type="submit" value="Submit Rating" class="btn btn-default" />
}
<p>@Html.ActionLink("Cancel", "Show", "Restaurant", new { id = @ViewBag.RestaurantId })</p>

BestRestaurant/Views/Rating/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Rating

<h2>Are you sure you want to delete this?</h2>
<br>
<p>@Html.DisplayFor(model => model.Score)</p>
<p>@Html.DisplayNameFor(model => model.Review): @Html.DisplayFor(model => model.Review)</p>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Cancel", "Show", "Restaurant", new { id = Model.RestaurantId })

<div class = "bottom">

</div>

BestRestaurant/Views/Rating/Edit.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurant.Models
@model BestRestaurant.Models.Rating;

<h5>Edit this Rating:</h5>
<br>
@using (Html.BeginForm())
{
  <div class ="form-group">
    @Html.HiddenFor(model => model.RatingId)
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Score)
    @Html.EditorFor(model => model.Score, new{ @class = "form-control"})
  
    @Html.LabelFor(model => model.Review)
    @Html.EditorFor(model => model.Review, new{ @class = "form-control"})
  </div>
  <input type="submit" value="Save" class="btn btn-default" />
}
<p>@Html.ActionLink("Cancel", "Show", "Restaurant", new { id = Model.RestaurantId })</p>

BestRestaurant/Views/Restaurant/Create.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurant.Models.Restaurant;

<h1>Add new Restaurant</h1>
<br>
@using (Html.BeginForm())
{
  <div class ="form-group">
  <h4>@Html.LabelFor(model => model.Name)</h4>
  @Html.TextBoxFor(model => model.Name, new{ @class = "form-control"})
  
  <h4>@Html.LabelFor(model => model.Location)</h4>
  @Html.TextBoxFor(model => model.Location, new{ @class = "form-control"})

  <h4>@Html.LabelFor(model => model.Rating)</h4>
  @Html.TextBoxFor(model => model.Rating, new{ @class = "form-control"})

  <h4>@Html.LabelFor(model => model.PhoneNumber)</h4>
  @Html.TextBoxFor(model => model.PhoneNumber, new{ @class = "form-control"})
  <h4>Cuisine</h4>@Html.DropDownList("CuisineId")
  <input type="submit" value="Add new restaurant" class="btn btn-default" />
  </div>
}
<div class="bottom">
<p>@Html.ActionLink("Show all restaurants", "Index")</p>
<div>

BestRestaurant/Views/Restaurant/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>
<br>
<h5>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h5>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<div class = "bottom">
@Html.ActionLink("Back to List", "Index")
</div>

BestRestaurant/Views/Restaurant/Details.cshtml
@{
  Layout = "_Layout";
}

BestRestaurant/Views/Restaurant/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h1>Edit</h1>
<br>
<h5>Edit this task: @Html.DisplayFor(model => model.Name)</h5>
<br>
@using (Html.BeginForm())
{
  <div class ="form-group">
    @Html.HiddenFor(model => model.RestaurantId)

    <h4>@Html.LabelFor(model => model.Name)</h4>
    @Html.EditorFor(model => model.Name, new{ @class = "form-control"})

    <h4>@Html.LabelFor(model => model.Location)</h4>
    @Html.EditorFor(model => model.Location, new{ @class = "form-control"})

    <h4>@Html.LabelFor(model => model.Rating)</h4>
    @Html.EditorFor(model => model.Rating, new{ @class = "form-control"})

    <h4>@Html.LabelFor(model => model.PhoneNumber)</h4>
    @Html.EditorFor(model => model.PhoneNumber, new{ @class = "form-control"})
  
  <h5>Cuisine</h5>@Html.DropDownList("CuisineId")
  <input type="submit" value="Save" class="btn btn-default" />
 </div>
}
<div class = "bottom">
<p>@Html.ActionLink("Back to list", "Index")</p>
</div>

BestRestaurant/Views/Restaurant/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models
@model List<BestRestaurant.Models.Restaurant>

<h1>Restaurants</h1>
<br>
@if (Model.Count == 0)
{
  <p>No restaurants have been added</p>
}
<ul>
@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{@restaurant.Name}", "Show", new { id = restaurant.RestaurantId }) | @restaurant.Cuisine.Name</li>
}
</ul>
<div class="bottom">
<p>@Html.ActionLink("Add new restaurant", "Create")    ||    @Html.ActionLink("Home", "Index", "Home")</p>
</div>

BestRestaurant/Views/Restaurant/Show.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model BestRestaurant.Models.Restaurant;

<h1>Restaurant Details:</h1>
<br>
<h5>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h5>
<h5>@Html.DisplayNameFor(model => model.Location): @Html.DisplayFor(model => model.Location)</h5>
<h5>Average Rating: @ViewBag.avgScore</h5>
<h5>Phone Number: @Html.DisplayFor(model => model.PhoneNumber)</h5>
<h5>@Html.DisplayNameFor(model => model.Cuisine): @Html.ActionLink($"{Model.Cuisine.Name}", "Show", "Cuisine", new { id = Model.CuisineId })</h5>

<h3>Ratings</h3>
<br>
@if (Model.Ratings.Count == 0)
{
  <p>No ratings have been added</p>
}
<ul>
@foreach (Rating rating in Model.Ratings)
{
  <li>@rating.Review | @rating.Score | @Html.ActionLink("Edit", "Edit", "Rating", new {id = @rating.RatingId}) | @Html.ActionLink("Delete", "Delete", "Rating", new {id = @rating.RatingId})</li>
}
<p>@Html.ActionLink("Rate this Restaurant", "Create", "Rating", new { id = Model.RestaurantId })</p>

<div class="bottom">
<p>@Html.ActionLink("Back to list", "Index")   ||    @Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })    ||    @Html.ActionLink("Delete Item", "Delete", new { id = Model.RestaurantId })</p>
</div>

BestRestaurant/Views/Shared/Footer.cshtml
<div class="footer">
  <p>Created by Tyson Lackey and Chris Yoon</p>
</div>

BestRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
      @Html.Partial("Footer")
    </div>
  </body>
</html>